services:
  cypress:
    build:
      context: ./cypress-e2e
      dockerfile: Dockerfile
    working_dir: /e2e
    environment:
      - DISPLAY=${DISPLAY}
      - INTERACTIVE_MODE=${INTERACTIVE_MODE}
    network_mode: host
    stdin_open: true
    tty: true
    volumes:
      - ./cypress-e2e/cypress/videos:/e2e/cypress/videos
      - /tmp/.X11-unix:/tmp/.X11-unix  # Correct volume mount for X11 socket

