services:
  cypress:
    build:
      context: ../../
      dockerfile: shared/docker/cypress/Dockerfile
    working_dir: /e2e
    environment:
      - DISPLAY=${DISPLAY}
      - INTERACTIVE_MODE=${INTERACTIVE_MODE}
    network_mode: host
    stdin_open: true
    tty: true
    volumes:
      - ../../cypress-e2e/cypress/videos:/e2e/cypress/videos
      - ../../cypress-e2e/cypress/screenshots:/e2e/cypress/screenshots
      - ../../cypress-e2e/cypress/reports:/e2e/cypress/reports