name: Cypress Tests

on:
  push:
    branches:
      - main
      - feat/cypress-*
  pull_request:
    branches:
      - main
      - feat/cypress-*

jobs:
  cypress:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./cypress-e2e

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'

      - name: Install root dependencies (monorepo)
        run: yarn install
        working-directory: .

      - name: Run Cypress tests
        run: yarn cypress:run || true

      - name: Generate Cypress summary
        run: node ./generate-cypress-summary.js

      - name: Post Cypress result to PR
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body-path: ./cypress-e2e/cypress-summary.md

      - name: Post Cypress result to Commit
        if: github.event_name == 'push'
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.sha }}
          body-path: ./cypress-e2e/cypress-summary.md

      - name: Upload Cypress videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: ./cypress-e2e/cypress/videos/

      - name: Upload Cypress screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: ./cypress-e2e/cypress/screenshots/

      - name: Upload Cypress JSON reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-json-reports
          path: ./cypress-e2e/cypress/reports/