name: Lint & Format

on:
  push:
    branches: [main, feat/**]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Check formatting
        run: npm run format
